# Generated by Django 5.2.3 on 2025-07-02 08:24

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='photos/', variations={'large': (800, 600), 'thumbnail': (150, 150, True)})),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
