# Generated by Django 4.2 on 2025-07-02 11:26

from django.db import migrations
from pictures.migrations import AlterPictureField
import pictures.models

# This migration alters the ImageField (django-stdimage) to PictureField (django-pictures).
# Optional image_width and image_height fields can be added to optimize PictureField I/O.
# See: https://github.com/codingjoe/django-stdimage?tab=readme-ov-file#migration-instructions

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),  # last migration
    ]

    operations = [
        # Replace StdImageField/ImageField with PictureField to support responsive image handling
        AlterPictureField(
            model_name='photo',
            name='image',
            field=pictures.models.PictureField(upload_to='photos'),
        ),
    ]
