# Generated by Django 4.2 on 2025-07-02 11:42

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20250702_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=['3/2'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, pixel_densities=[1, 2], upload_to='photos'),
        ),
    ]
